if &compatible
    set nocompatible
endif
set runtimepath+=$HOME/.cache/dein/repos/github.com/Shougo/dein.vim

execute 'source' fnameescape(expand('$XDG_CONFIG_HOME/vim/rc/dein.rc.vim'))

filetype plugin indent on
syntax enable

set number relativenumber

" Keymapping timeout
set timeout timeoutlen=3000 ttimeoutlen=100

" Text Formatting
set autoindent
set nowrap
set softtabstop=4
set shiftwidth=4
set tabstop=4
set expandtab
set textwidth=80

" Make sure Lightline shows up
set laststatus=2

set mouse=a

let base16colorspace=256
colorscheme base16-materia
