if &compatible
  set nocompatible
endif

call plug#begin(expand('$XDG_DATA_HOME/plugged'))

" Plug 'sheerun/vim-polyglot', has('nvim') ? { 'on': [] } : {}

Plug 'itchyny/lightline.vim'
Plug 'chriskempson/base16-vim'

Plug expand('$DOTFILES/opt/fzf'), { 'do': { -> fzf#install() } }
  nnoremap <C-p> :<C-u>FZF<CR>

Plug 'nvim-treesitter/nvim-treesitter', has('nvim') ? {'do': ':TSUpdate'} : { 'on': [] }

Plug 'mhinz/vim-signify'
  let g:signify_sign_add               = '│'
  let g:signify_sign_delete            = '│'
  let g:signify_sign_delete_first_line = '│'
  let g:signify_sign_change            = '│'
  let g:signify_sign_change_delete     = '│'

call plug#end()

" filetype plugin indent on
" syntax enable

set number relativenumber

" Trigger async updates faster
set updatetime=100

" Text Formatting
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab smarttab
set textwidth=80
set nowrap

" Keymapping timeout
set timeout timeoutlen=3000 ttimeoutlen=100

" Search as you type - Vim defaults to false
set incsearch

" Make sure Lightline shows up
set laststatus=2

set mouse=a

" Recommended on the archwiki https://wiki.archlinux.org/title/St#Vim
" for making termguicolors work (needed for vim but not nvim)
set t_8f=[38;2;%lu;%lu;%lum        " set foreground color
set t_8b=[48;2;%lu;%lu;%lum        " set background color
set t_Co=256
let base16colorspace=256
colorscheme base16-materia
set termguicolors
